//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietdonhang
    {
        public string soluong { get; set; }
        public string madh { get; set; }
        public string masach { get; set; }
        public string dongia { get; set; }
    
        public virtual Donhang Donhang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
