//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Sach
    {
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
        }
    
    
        public string masach { get; set; }
        public string tensach { get; set; }
        public Nullable<decimal> giaban { get; set; }
        [AllowHtml]
        public string mota { get; set; }
        public string anhbia { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string soluongton { get; set; }
        public string manxb { get; set; }
        public string machude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual Chude Chude { get; set; }
        public virtual Nhaxuatban Nhaxuatban { get; set; }
    }
}
