//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tacgia
    {
        public string matacgia { get; set; }
        public string tentacgia { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
    }
}
